apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-add-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-add-tasks-api
  template:
    metadata:
      labels:
        app: todo-add-tasks-api
    spec:
      containers:
      - name: todo-add-tasks-api
        image: acrprodtodoapp.azurecr.io/add-task:v1
        ports:
        - containerPort: 8000
        env: 
        - name: "CONNECTION_STRING"
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-prod-todoapp.database.windows.net,1433;Database=sqldb-prod-todoapp;Uid=devopsadmin;Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
