
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  addtask-todo-microservice
spec:
  ingressClassName: nginx
  rules:
    - host: addtask-todo-microservice.manpura.shop
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: addtask-todo-microservice
                port:
                  number: 80
